name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        run: |
          TimeStamp=$(date +%s)
          TimeStamp="uptrain-${TimeStamp}"
          docker build -t $TimeStamp .

      - name: Compress Image
        run: docker save -o ${{ github.workspace }}/${{ env.TimeStamp }}.tar ${{ env.TimeStamp }}

      - name: Copy Image to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: 65.2.63.83
          username: ubuntu
          key: ${{ secrets.PEM_FILE }}
          source: ${{ github.workspace }}/${{ env.TimeStamp }}.tar
          target: /home/ubuntu/${{ env.TimeStamp }}.tar

      - name: Load Image on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: 65.2.63.83
          username: ubuntu
          key: ${{ secrets.PEM_FILE }}
          script: |
            docker load < /home/ubuntu/${{ env.TimeStamp }}.tar
            export image_build=${{ env.TimeStamp }}
            docker-compose up -d --build
            find . -name 'uptrain*.tar' -delete
            docker image prune -a -f

      - name: Garbage Collection
        run: |
          docker image prune -a -f
          find . -name 'uptrain*.tar' -delete
